#############################
# MegaLinter configuration  #
#############################

# Limit scope to Python linters and relax strict ones to reduce CI noise
APPLY_FIXES: none
PRINT_ALPACA: false

DISABLE_LINTERS:
  # Keep only Black, Flake8 and Isort for Python
  - PYTHON_PYLINT
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_PYDOCSTYLE
  - PYTHON_BANDIT
  - PYTHON_RUFF

# Exclude non-source or generated directories
FILTER_REGEX_EXCLUDE: >-
  (^checkpoint/|^saved_model/|^images/|^\.venv/|^venv/|^\.git/|^.*\.ipynb$)

# Keep default Python linters enabled by the Python flavor:
# - PYTHON_BLACK
# - PYTHON_FLAKE8
# - PYTHON_ISORT

# Fail the job only on errors (not warnings)
DEFAULT_FAILURE_THRESHOLD: error


